# Generated by Django 4.1.3 on 2022-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='courses',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
