# Generated by Django 4.1.4 on 2022-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='courses',
        ),
    ]
